[package]
name = "phasmix_fit"
version = "0.0.0"
edition = "2024"

[dependencies]
basin= { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
rayon = { workspace = true }
wide = { workspace = true }
phasmix_core = { workspace = true }
phasmix_math = { workspace = true }
phasmix_mock = { workspace = true }
phasmix_opt = { workspace = true }

[lints]
workspace = true
